version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build Docker image
      - docker build -t react-app .
      - docker tag react-app:latest <AWS_ACCOUNT_ID>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/react-app:latest
  post_build:
    commands:
      - echo Push Docker image to ECR
      - docker push <AWS_ACCOUNT_ID>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/react-app:latest
      - printf '[{"name":"react-app","imageUri":"%s"}]' <AWS_ACCOUNT_ID>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/react-app:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
